# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  #- name: Tour
  #  url: tour
  #  weight: 10
  - name: Monkeypox Severity Score Development and Validation
    url: mpx_dev_val
    weight: 20
  - name: Tool
    identifier: tool
    weight: 30
  - name: Download the tool
    PageRef: tool/tool_dl/index.md
    weight: 10
    parent: tool
  - name: Calculate online
    PageRef: tool/tool_calc/index.md
    weight: 20
    parent: tool
  - name: Publications
    url: publication
    weight: 37
  - name: Team
    url: people
    weight: 40
  - name: Contact
    url: contact
    weight: 50

